let questions = [
    {
        "question": "Was ist die Hauptstadt von Frankreich?",
        "answer_1": "Berlin",
        "answer_2": "Madrid",
        "answer_3": "Paris",
        "answer_4": "Rom",
        "right_answer": 3,
    },
    {
        "question": "Welches Element hat das chemische Symbol H?",
        "answer_1": "Helium",
        "answer_2": "Wasserstoff",
        "answer_3": "Kohlenstoff",
        "answer_4": "Stickstoff",
        "right_answer": 2,
    },
    {
        "question": "Wie viele Kontinente gibt es auf der Erde?",
        "answer_1": "5",
        "answer_2": "6",
        "answer_3": "7",
        "answer_4": "8",
        "right_answer": 3,
    },
    {
        "question": "Wer hat die Relativitätstheorie formuliert?",
        "answer_1": "Isaac Newton",
        "answer_2": "Galileo Galilei",
        "answer_3": "Albert Einstein",
        "answer_4": "Nikola Tesla",
        "right_answer": 3,
    },
    {
        "question": "Welche Farbe hat Chlorophyll?",
        "answer_1": "Rot",
        "answer_2": "Blau",
        "answer_3": "Gelb",
        "answer_4": "Grün",
        "right_answer": 4,
    },
    {
        "question": "Wie viele Planeten hat unser Sonnensystem?",
        "answer_1": "7",
        "answer_2": "8",
        "answer_3": "9",
        "answer_4": "10",
        "right_answer": 2,
    },
    {
        "question": "Wer schrieb 'Die Verwandlung'?",
        "answer_1": "Thomas Mann",
        "answer_2": "Franz Kafka",
        "answer_3": "Hermann Hesse",
        "answer_4": "Johann Wolfgang von Goethe",
        "right_answer": 2,
    },
    {
        "question": "Welche ist die kleinste Einheit des Lebens?",
        "answer_1": "Atom",
        "answer_2": "Molekül",
        "answer_3": "Zelle",
        "answer_4": "Organ",
        "right_answer": 3,
    },
    {
        "question": "Wie viele Beine hat eine Spinne?",
        "answer_1": "6",
        "answer_2": "8",
        "answer_3": "10",
        "answer_4": "12",
        "right_answer": 2,
    },
    {
        "question": "Welcher Planet wird oft als 'roter Planet' bezeichnet?",
        "answer_1": "Venus",
        "answer_2": "Mars",
        "answer_3": "Jupiter",
        "answer_4": "Saturn",
        "right_answer": 2,
    },
];